# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='psyonic_ability_hand',
    version='0.1.0',
    packages=['psyonic_ability_hand'],
    package_dir={"": "src"},
    package_data={},
    install_requires=[
        'aiofiles==0.8.0', 'colorama==0.4.4', 'commonmark==0.9.1',
        'evdev==1.5.0', 'loguru==0.6.0', 'numpy==1.22.3', 'pygments==2.12.0',
        'pyserial==3.5', 'rich==12.3.0', 'smbus2==0.4.1',
        'typing-extensions==4.2.0', 'win32-setctime==1.1.0'
    ],
)
